// SPDX-License-Identifier: MIT
// Public API checks: attachment writes are recorded before seeking, names survive capture,
// and repeated navigation leaves sorted, unique usage at the original event.
#include <cstdio>
#include <cstring>
#include "renderdoc/api/replay/renderdoc_replay.h"
REPLAY_PROGRAM_MARKER()

static bool HasUsage(IReplayController *controller, ResourceId resource, uint32_t event,
                     ResourceUsage type)
{
  const auto usage = controller->GetUsage(resource);
  bool found = false;
  for(size_t i = 0; i < usage.size(); i++)
  {
    if(i && !(usage[i - 1] < usage[i])) return false;
    found |= usage[i].eventId == event && usage[i].usage == type;
  }
  return found;
}

static void Draws(const rdcarray<ActionDescription> &actions, rdcarray<uint32_t> &events)
{
  for(const auto &action : actions)
  {
    if(action.flags & (ActionFlags::Drawcall | ActionFlags::MeshDispatch))
      events.push_back(action.eventId);
    Draws(action.children, events);
  }
}

int main(int argc, char **argv)
{
  if(argc < 2 || argc > 3) return 2;
  GlobalEnvironment env; env.enumerateGPUs = false;
  rdcarray<rdcstr> args = {argv[0]}; RENDERDOC_InitialiseReplay(env, args);
  auto file = RENDERDOC_OpenCaptureFile();
  auto status = file->OpenFile(argv[1], "rdc", nullptr);
  IReplayController *controller = nullptr;
  if(status.OK()) rdctie(status, controller) = file->OpenCapture(ReplayOptions(), nullptr);
  file->Shutdown();
  if(!status.OK() || !controller) return 3;
  int result = 0;
  if(argc == 3 && strcmp(argv[2], "--labels") == 0)
  {
    bool texture = false, buffer = false;
    for(const auto &resource : controller->GetResources())
    {
      if(resource.type == ResourceType::Texture && !resource.autogeneratedName &&
         resource.name == "GBufferA")
      {
        texture = true;
        bool clear = false, copy = false;
        for(const auto &use : controller->GetUsage(resource.resourceId))
        {
          clear |= use.usage == ResourceUsage::Clear;
          copy |= use.usage == ResourceUsage::CopySrc;
        }
        // The view variant clears/copies a distinct view object; its parent must still report
        // both operations, without inferring aliases from heap addresses.
        if(!clear || !copy) result = 9;
      }
      buffer |= resource.type == ResourceType::Buffer && !resource.autogeneratedName &&
                resource.name == "Readback 名称";
      if(resource.name.contains("Old ")) result = 4;
    }
    if(!texture || !buffer) result = 4;
    printf("labels frame_texture=%d preframe_buffer_utf8=%d\n", texture, buffer);
  }
  rdcarray<uint32_t> events;
  Draws(controller->GetRootActions(), events);
  for(uint32_t event : events)
  {
    controller->SetFrameEvent(event, true);
    auto state = controller->GetPipelineState().GetMetalPipelineState();
    for(const auto &attachment : state->colorTargets)
      if(attachment.resource != ResourceId() &&
         !HasUsage(controller, attachment.resource, event, ResourceUsage::ColorTarget)) result = 5;
    if(state->depthTarget.resource != ResourceId() &&
       !HasUsage(controller, state->depthTarget.resource, event,
                 ResourceUsage::DepthStencilTarget)) result = 6;
    auto baseline = state->colorTargets;
    for(unsigned cycle = 0; cycle < 2; cycle++)
    {
      controller->SetFrameEvent(0, true); controller->SetFrameEvent(event, true);
      if(!controller->GetFatalErrorStatus().OK()) result = 7;
      for(const auto &attachment : baseline)
        if(attachment.resource != ResourceId() &&
           !HasUsage(controller, attachment.resource, event, ResourceUsage::ColorTarget)) result = 8;
    }
    printf("attachment usage event=%u checked\n", event);
  }
  controller->Shutdown(); RENDERDOC_ShutdownReplay();
  if(!result) puts("PASS resource names and sorted unique attachment usage through EID0 resets");
  return result;
}
