// SPDX-License-Identifier: MIT
// Normal capture open followed by explicit UE event seeks and Native MRT readbacks.
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include "renderdoc/api/replay/renderdoc_replay.h"
REPLAY_PROGRAM_MARKER()

static unsigned long long IDValue(ResourceId id)
{
  uint64_t value = 0; static_assert(sizeof(id) == sizeof(value), "ResourceId width");
  memcpy(&value, &id, sizeof(value)); return value;
}

static const char *UsageName(ResourceUsage usage)
{
  switch(usage)
  {
    case ResourceUsage::Clear: return "Clear";
    case ResourceUsage::ColorTarget: return "ColorTarget";
    case ResourceUsage::DepthStencilTarget: return "DepthStencilTarget";
    case ResourceUsage::VS_Resource: return "VS_Resource";
    case ResourceUsage::PS_Resource: return "PS_Resource";
    case ResourceUsage::CS_Resource: return "CS_Resource";
    case ResourceUsage::CS_RWResource: return "CS_RWResource";
    default: return "Other";
  }
}

static bool PrintUsage(IReplayController *controller, ResourceId id, uint32_t selected)
{
  for(const auto &resource : controller->GetResources())
    if(resource.resourceId == id)
      printf("UE resource=%llu name=%s autogenerated=%d\n", IDValue(id),
             resource.name.c_str(), resource.autogeneratedName);
  const auto usage = controller->GetUsage(id);
  for(size_t i = 0; i < usage.size(); i++)
  {
    if(i && !(usage[i - 1] < usage[i])) return false;
    printf("UE usage resource=%llu selected=%u event=%u type=%s enum=%u\n", IDValue(id),
           selected, usage[i].eventId, UsageName(usage[i].usage), uint32_t(usage[i].usage));
  }
  printf("UE usage resource=%llu selected=%u count=%zu sorted_unique=1\n",
         IDValue(id), selected, usage.size());
  return true;
}

static void Inventory(const rdcarray<ActionDescription> &actions,
                      const rdcarray<TextureDescription> &textures, const SDFile &structured)
{
  for(const auto &a : actions)
  {
    unsigned colorCount = 0;
    for(ResourceId output : a.outputs)
      if(output != ResourceId()) colorCount++;
    if(colorCount >= 3)
      printf("UE multiple-output action EID=%u targets=%u name=%s\n", a.eventId,
             colorCount, a.customName.c_str());
    for(const auto &t : textures)
      if(t.depth == 64 && t.width == 64 && t.height == 64 &&
         a.flags & ActionFlags::Drawcall && a.outputs.contains(t.resourceId))
        printf("UE volume MRT draw EID=%u resource=%llu instances=%u\n", a.eventId,
               IDValue(t.resourceId), a.numInstances);
    if((a.flags & ActionFlags::Dispatch) && (a.flags & ActionFlags::Indirect))
      for(const auto &event : a.events)
        if(event.chunkIndex < structured.chunks.size())
        {
          const auto *chunk = structured.chunks[event.chunkIndex];
          const auto *buffer = chunk->FindChild("indirectBuffer");
          const auto *offset = chunk->FindChild("indirectBufferOffset");
          if(buffer && offset)
            printf("UE indirect action EID=%u buffer=%llu offset=%llu groups=%u,%u,%u name=%s\n",
                   a.eventId, (unsigned long long)buffer->AsUInt64(),
                   (unsigned long long)offset->AsUInt64(), a.dispatchDimension[0],
                   a.dispatchDimension[1], a.dispatchDimension[2], a.customName.c_str());
        }
    Inventory(a.children, textures, structured);
  }
}

static bool WriteActions(FILE *out, const rdcarray<ActionDescription> &actions,
                         unsigned depth, uint32_t &last)
{
  for(const auto &a : actions)
  {
    if(!a.IsFakeMarker())
    {
      if(a.eventId <= last) return false;
      last = a.eventId;
    }
    fprintf(out, "%u\t%u\t%d\t%s\n", a.eventId, depth,
            a.IsFakeMarker() ? 1 : 0, a.customName.c_str());
    if(!WriteActions(out, a.children, depth + 1, last)) return false;
  }
  return true;
}

int main(int argc, char **argv)
{
  if(argc < 4) return 2;
  struct IndirectCheck { unsigned eid; unsigned long long buffer, offset; unsigned words[3]; };
  rdcarray<IndirectCheck> checks;
  for(int arg = 3; arg < argc; arg++)
    if(strncmp(argv[arg], "--indirect=", 11) == 0)
    {
      IndirectCheck check = {};
      if(sscanf(argv[arg] + 11, "%u,%llu,%llu,%u,%u,%u", &check.eid,
                &check.buffer, &check.offset, &check.words[0], &check.words[1],
                &check.words[2]) != 6) return 2;
      checks.push_back(check);
    }
  setvbuf(stdout, nullptr, _IONBF, 0);
  char debugPath[4096];
  snprintf(debugPath, sizeof(debugPath), "%s/renderdoc.log", argv[2]);
  RENDERDOC_SetDebugLogFile(debugPath);
  GlobalEnvironment env; env.enumerateGPUs = false;
  rdcarray<rdcstr> args; args.push_back(argv[0]); RENDERDOC_InitialiseReplay(env, args);
  auto file = RENDERDOC_OpenCaptureFile();
  auto status = file->OpenFile(argv[1], "rdc", nullptr);
  if(!status.OK()) return 3;
  IReplayController *c = nullptr;
  rdctie(status, c) = file->OpenCapture(ReplayOptions(), nullptr); file->Shutdown();
  if(!status.OK() || !c) return 4;
  puts("UE normal OpenCapture OK"); Inventory(c->GetRootActions(), c->GetTextures(), c->GetStructuredFile());
  int exitCode = 0;
  bool inspectShaders = false;
  for(int arg = 3; arg < argc; arg++) inspectShaders |= strcmp(argv[arg], "--inspect-shaders") == 0;
  if(inspectShaders)
    for(const rdcstr &target : c->GetDisassemblyTargets(true))
      printf("UE disassembly target=%s\n", target.c_str());
  rdcarray<ResourceId> extraTextures;
  rdcarray<ResourceId> usageResources;
  for(int arg = 3; arg < argc; arg++)
    if(strncmp(argv[arg], "--texture=", 10) == 0)
    {
      uint64_t value = strtoull(argv[arg] + 10, nullptr, 10); ResourceId id;
      memcpy(&id, &value, sizeof(id)); extraTextures.push_back(id);
    }
    else if(strncmp(argv[arg], "--usage=", 8) == 0)
    {
      uint64_t value = strtoull(argv[arg] + 8, nullptr, 10); ResourceId id;
      memcpy(&id, &value, sizeof(id)); usageResources.push_back(id);
    }
  for(ResourceId id : usageResources)
    if(!PrintUsage(c, id, 0)) exitCode = 13;
  snprintf(debugPath, sizeof(debugPath), "%s/actions.tsv", argv[2]);
  if(FILE *tree = fopen(debugPath, "wb"))
  {
    uint32_t last = 0;
    const bool ordered = WriteActions(tree, c->GetRootActions(), 0, last);
    fclose(tree);
    printf("UE action tree chronological=%d last=%u\n", ordered ? 1 : 0, last);
    if(!ordered) exitCode = 12;
  }
  else exitCode = 9;
  for(int arg = 3; arg < argc && !exitCode; arg++)
  {
    if(strncmp(argv[arg], "--", 2) == 0) continue;
    const uint32_t eid = uint32_t(strtoul(argv[arg], nullptr, 10));
    rdcarray<Descriptor> outputs;
    rdcarray<bytebuf> baseline;
    for(unsigned cycle = 0; cycle < 2 && !exitCode; cycle++)
    {
      c->SetFrameEvent(0, true); c->SetFrameEvent(eid, true);
      status = c->GetFatalErrorStatus();
      if(!status.OK())
      {
        fprintf(stderr, "UE event failed EID=%u cycle=%u: %s\n", eid, cycle,
                status.internal_msg ? status.internal_msg->c_str() : "unknown");
        exitCode = 5; break;
      }
      const auto *state = c->GetPipelineState().GetMetalPipelineState();
      printf("UE pipeline EID=%u render=%llu compute=%llu fragmentShader=%llu computeShader=%llu fragmentBindings=%zu computeBindings=%zu\n",
             eid, IDValue(state->pipelineResourceId), IDValue(state->computePipelineResourceId),
             IDValue(state->fragmentShader.resourceId), IDValue(state->computeShader.resourceId),
             state->fragmentBuffers.size(), state->computeBuffers.size());
      if(inspectShaders)
      {
        for(const auto &input : c->GetDescriptorAccess())
        {
          if(input.staticallyUnused) continue;
          DescriptorRange range; range.type = input.type; range.offset = input.byteOffset;
          range.descriptorSize = input.byteSize; range.count = 1;
          const auto descriptors = c->GetDescriptors(input.descriptorStore, {range});
          const auto locations = c->GetDescriptorLocations(input.descriptorStore, {range});
          printf("UE descriptor EID=%u cycle=%u stage=%u type=%u store=%llu offset=%u resource=%llu\n",
              eid, cycle, uint32_t(input.stage), uint32_t(input.type), IDValue(input.descriptorStore), input.byteOffset,
              descriptors.empty() ? 0ULL : IDValue(descriptors[0].resource));
          printf("UE fragment location EID=%u offset=%u name=%s\n", eid, input.byteOffset,
                 locations.empty() ? "" : locations[0].logicalBindName.c_str());
        }
        const bool compute = state->computeShader.resourceId != ResourceId();
        auto refl = compute ? state->computeShader.reflection : state->fragmentShader.reflection;
        auto text = c->DisassembleShader(compute ? state->computePipelineResourceId : state->pipelineResourceId, refl, "Metal AIR (Apple toolchain)");
        char path[4096]; snprintf(path, sizeof(path), "%s/eid-%u-%s-air.txt", argv[2], eid, compute ? "compute" : "fragment");
        if(FILE *out = fopen(path, "wb")) { fwrite(text.data(), 1, text.size(), out); fclose(out); }
        printf("UE AIR shader bytes=%zu sample_texture=%d\n", text.size(), text.find("@air.sample_texture_") >= 0);
      }
      for(ResourceId id : usageResources)
        if(!PrintUsage(c, id, eid)) exitCode = 13;
      if(exitCode) break;
      auto current = state->colorTargets;
      for(ResourceId id : extraTextures) { Descriptor extra; extra.resource = id; current.push_back(extra); }
      if(!cycle) outputs = current;
      if(outputs != current) { exitCode = 6; break; }
      printf("UE event seek OK EID=%u cycle=%u targets=%zu\n", eid, cycle, current.size());
      for(const auto &check : checks)
        if(check.eid == eid)
        {
          ResourceId resource;
          uint64_t id = check.buffer; memcpy(&resource, &id, sizeof(id));
          const auto bytes = c->GetBufferData(resource, check.offset, 12);
          unsigned actual[3] = {};
          if(bytes.size() == 12) memcpy(actual, bytes.data(), 12);
          printf("UE Native indirect EID=%u cycle=%u buffer=%llu offset=%llu actual=%u,%u,%u expected=%u,%u,%u\n",
                 eid, cycle, check.buffer, check.offset, actual[0], actual[1], actual[2],
                 check.words[0], check.words[1], check.words[2]);
          if(bytes.size() != 12 || memcmp(actual, check.words, 12)) { exitCode = 11; break; }
        }
      if(exitCode) break;
      unsigned index = 0;
      for(const auto &target : current)
      {
        if(target.resource == ResourceId()) continue;
        const auto bytes = c->GetTextureData(target.resource,
                                           {target.firstMip, target.firstSlice, 0});
        if(bytes.empty()) { exitCode = 7; break; }
        if(!cycle) baseline.push_back(bytes);
        else if(index >= baseline.size() || baseline[index] != bytes)
        { fprintf(stderr, "UE MRT data mismatch EID=%u target=%u\n", eid, index); exitCode = 8; break; }
        char path[4096];
        snprintf(path, sizeof(path), "%s/eid-%u-cycle-%u-target-%u.bin", argv[2], eid, cycle, index);
        FILE *out = fopen(path, "wb");
        if(!out) { exitCode = 9; break; }
        const bool saved = fwrite(bytes.data(), 1, bytes.size(), out) == bytes.size(); fclose(out);
        if(!saved) { exitCode = 10; break; }
        printf("UE Native MRT EID=%u cycle=%u target=%u resource=%llu mip=%u slice=%u bytes=%zu\n",
               eid, cycle, index++, IDValue(target.resource),
               target.firstMip, target.firstSlice, bytes.size());
      }
    }
  }
  rdcstr debugContents;
  RENDERDOC_GetLogFileContents(0, debugContents);
  snprintf(debugPath, sizeof(debugPath), "%s/renderdoc-final.log", argv[2]);
  if(FILE *debugOutput = fopen(debugPath, "wb"))
  {
    fwrite(debugContents.c_str(), 1, debugContents.size(), debugOutput);
    fclose(debugOutput);
  }
  c->Shutdown(); RENDERDOC_ShutdownReplay();
  if(!exitCode) puts("PASS UE selected events, EID0 resets and identical Native MRT bytes");
  return exitCode;
}
